# Generated by Django 5.0.7 on 2024-07-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcuentas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Remito',
        ),
    ]
