# Generated by Django 5.0.7 on 2024-07-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appcuentas', '0002_delete_cliente_delete_compra_delete_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('cuit', models.CharField(max_length=13)),
                ('telefono', models.CharField(max_length=20)),
                ('deuda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoRemito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcuentas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('deuda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('remito_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appcuentas.remito')),
                ('proveedor', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=('appcuentas.remito',),
        ),
        migrations.AddField(
            model_name='remito',
            name='productos',
            field=models.ManyToManyField(through='appcuentas.ProductoRemito', to='appcuentas.producto'),
        ),
        migrations.AddField(
            model_name='productoremito',
            name='remito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcuentas.remito'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('remito_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appcuentas.remito')),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='appcuentas.cliente')),
            ],
            bases=('appcuentas.remito',),
        ),
    ]
